### PR TITLE
V1.2.4 Pull request

### PR DESCRIPTION
**Pull request by wilmTap**
Contains the additions and loosened constraints discussed at the meeting Monday 6 June

### CODE REVIEW

**Comment by robwynj** [comment]
Hi Wilbert,

My understanding was that v1.2.4 would include non-breaking UDD changes and be deployed immediately for HT2's API to be updated too ASAP (and therefore no UDD field movements/ additions/ deletions or structure/ ER changes - these would be included in a future UDD v1.3?

Comments are therefore:

Make WITHDRAWAL_DATE as OPTIONAL for v1.2.4 should also be provided...

So for v1.2.4 I would assume the above list you provided via GitHub - but EXCLUDING the following:

•	Added tenant ID
•	Moved max points
•	Adding COURSE_JOIN_DATE to student course membership
•	Deleted WITHDRAWAL_DATE from student course membership
•	Moved COURSE_LOCATION **(BUT STILL MAKE THIS OPTIONAL FOR v1.2.4)**
•	Reinstated WITHDRAWAL_DATE **(SHOULD NOT BE REMOVED SO IS N/A)**

Let me know what you think.

Kind Regards,

Rob

**Comment by arc12** [comment]
I think we should be clear about "breaking" and change.

For 1.2.4, a sensible interpretation would be "changes that do not require code change in SSP or the student app and which can be accommodated by HT2 before Andrew goes on hols".

For 1.3, a sensible interpretation would be "changes that do not require code change in SSP or the student app and which can be accommodated by HT2 in a reasonable time-frame, including applying code which will allow features to be deprecated without breaking SSP/App (e.g. the max points issue we discussed yesterday)"

As a general rule, I think we should only consider a change to be breaking if one of the parties involved in the project would actually have something break and is unwilling to change. i.e. to NOT define breaking changes in terms of the specification but what is realistic in terms of code change. So: adding an optional field could conceivably fit into 1.2.4

Adam

**Comment by robwynj** [comment]
Hi Adam,

I am just more concerned about the here and now and the HEI/ FEI's submitting and prepping data now - and breaking changes will change how they provide the data (they already had a raft of changes recently), and I don't want to introduce any additional work/ time-delay in data coming back from them for impending milestones/ dependencies with UNICON too.

I am just thinking short term ie. for now, for v1.2.4 I want non-breaking changes in which make and improve validation (API) and allows UDD to work as it should (the HEI's are in the process/ nearly done or already submitted UDD data to us for LAP - and i'm in the middle of processing validations too) - so am asking for a small window and period of stability during the crucial stage of data transfer/ assimilation) - I agree with what you've said above, but for the v1.2.4 we need stability for our customers :)

Kind Regards

Rob

**Comment by michaelwebbjisc** [comment]
Agreed - this is something I missed in yesterday's discussion, but any change that requires institutions to provide data differently would be considered a breaking change by us.

**Comment by arc12** [comment]
"but any change that requires institutions [or others like us ;-)] to provide data differently would be considered a breaking change by us."

I concur with the principle... IF there is risk attached. Adding a requirement everyone is happy with is not an absolute problem. (it may, of course not be possible to determine happiness in a reasonable time-frame)

Also, please try to reduce future impact. For example: adding a field in 1.2.4 as optional would (so long as HT2 can accommodate it in the desired time period) not break existing ETLs but would allow those who can move forward to do so now, reducing the impact of rework on them in the future. Making something mandatory... more of a deal!

Adam

**Comment by michaelwebbjisc** [comment]
@arc12 agreed.

**Comment by wilmTap** [comment]
OK, I understood that v1.2.4 was to include any loosening of requirements from mandatory to optional, and any additions of new properties. 
I will now interpret it as any loosening of requirements from mandatory to optional, and any additions of _optional_ new properties. Moreover, any new properties that will become or might become mandatory in later versions of the UDD, will be included in v1.2.4 as optional.

I'll go through the issues and re-assign which change happens in which version, and then amend the branches accordingly.

**Comment by wilmTap** [comment]
I've just updated the v1.2.4 branch in line with the new interpretation above. Compared to 1.2.3, here's what's new:

#46 Added an optional TENANT_ID to course
#50 Added an optional COURSE_JOIN_DATE to Student Course Membership
#63 Added all reference relations between all entities in the entity relation diagram, and updated it
#64 COURSE_AIM_ATTAINED on student course membership made optional
#65 TUTOR_STAFF_ID on Student (additional) made optional 
#67 All 1-100 range mark ranges changed to 0-100
#68 COURSE_LOCATION made optional (but still on Student on course instance)
#69 WITHDRAWAL_REASON and WITHDRAWAL_DATE made optional
#70 Added cardinality constraints to all properties on all entities
#71 Added an optional JOIN_AGE to student course membership

**Pull request merged**
